
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-09-28T12:10:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "47f691cad9dbcec389a1db374cd85dd44282d3a4",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
